CREATE TABLE `titulos_publicos` (
  `id` int NOT NULL AUTO_INCREMENT,
  `insert_timestamp` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_timestamp` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `tipo_titulo` varchar(45) NOT NULL,
  `expressao` varchar(45) DEFAULT NULL,
  `data_vencimento` date NOT NULL,
  `data_referencia` date NOT NULL,
  `codigo_selic` varchar(45) DEFAULT NULL,
  `data_base` date DEFAULT NULL,
  `taxa_compra` decimal(15,10) DEFAULT NULL,
  `taxa_venda` decimal(15,10) DEFAULT NULL,
  `taxa_indicativa` decimal(15,10) NOT NULL,
  `intervalo_min_d0` decimal(15,10) DEFAULT NULL,
  `intervalo_max_d0` decimal(15,10) DEFAULT NULL,
  `intervalo_min_d1` decimal(15,10) DEFAULT NULL,
  `intervalo_max_d1` decimal(15,10) DEFAULT NULL,
  `pu` decimal(20,10) DEFAULT NULL,
  `pu_calc` decimal(20,10) DEFAULT NULL,
  `pm` decimal(20,10) DEFAULT NULL,
  `duration` decimal(20,10) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci